### PR TITLE
[IMP] product_template_tags: Now it is possible to group the tags.

### PR DESCRIPTION
**Pull request by nhomar**
Just for the sake of the:

proiduct_parent_tag

### CODE REVIEW

**Comment by angelesgl17** [comment]
+1 @nhomar

**Comment by hugho-ad** [comment]
@nhomar shall we forward this to OCA?

**Comment by luisg123v** [comment]
@hugho-ad,

This shouldn't been merged in the first place, because this prevents us from updating the repo.

Unfortunately, I will have to rever this.

Please either add this PR as a patch or implement these same changes in the customer repo.

Regards,

**Comment by hugho-ad** [comment]
@EmilioSerna 

pls. lets move this change to 15.0-lavop

**Comment by hugho-ad** [comment]
@luisg123v 

did you already reverted this?

you simply made the push -f with only oca commits right?

**Comment by hugho-ad** [comment]
@EmilioSerna 

I just created 15.0-villagroup branch, that is holding this customization, could you pls open a MR on villa project to update the repo and branch on oca_dependencies

https://github.com/Vauxoo/product-attribute/tree/15.0-villagroup

**Comment by EmilioSerna** [comment]
> @EmilioSerna
> 
> I just created 15.0-villagroup branch, that is holding this customization, could you pls open a MR on villa project to update the repo and branch on oca_dependencies
> 
> https://github.com/Vauxoo/product-attribute/tree/15.0-villagroup

@hugho-ad 

Merge Request created
https://git.vauxoo.com/vauxoo/villagroup/-/merge_requests/769

**Comment by luisg123v** [comment]
> did you already reverted this?

@hugho-ad 

Yes, I did.

**Pull request merged**
